# Generated by Django 4.1.7 on 2023-03-12 17:37

import WeatherApp.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[WeatherApp.accounts.models.is_adult]),
        ),
    ]
